<!DOCTYPE html>
<html lang="en-US">
  <head>
    <meta charset='utf-8'>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <link rel="stylesheet" href="/assets/css/style.css?v=98b01076f4eee0a60ca6e354decb56c9c8e08869" media="screen" type="text/css">
    <link rel="stylesheet" href="/assets/css/print.css" media="print" type="text/css">

    <!--[if lt IE 9]>
    <script src="//html5shiv.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

<!-- Begin Jekyll SEO tag v2.5.0 -->
<title>verror: rich JavaScript errors | karx.github.io</title>
<meta name="generator" content="Jekyll v3.8.5" />
<meta property="og:title" content="verror: rich JavaScript errors" />
<meta property="og:locale" content="en_US" />
<meta name="description" content="Open channel for karx compute system interactions" />
<meta property="og:description" content="Open channel for karx compute system interactions" />
<link rel="canonical" href="http://localhost:4000/FlutterArsenal/fromgithub/node_modules/verror/" />
<meta property="og:url" content="http://localhost:4000/FlutterArsenal/fromgithub/node_modules/verror/" />
<meta property="og:site_name" content="karx.github.io" />
<script type="application/ld+json">
{"description":"Open channel for karx compute system interactions","@type":"WebPage","headline":"verror: rich JavaScript errors","url":"http://localhost:4000/FlutterArsenal/fromgithub/node_modules/verror/","@context":"http://schema.org"}</script>
<!-- End Jekyll SEO tag -->

  </head>

  <body>
    <header>
      <div class="inner">
        <a href="http://localhost:4000/">
          <h1>karx.github.io</h1>
        </a>
        <h2>Open channel for karx compute system interactions</h2>
        
          <a href="https://github.com/karx/karx.github.io" class="button"><small>View project on</small> GitHub</a>
        
        
      </div>
    </header>

    <div id="content-wrapper">
      <div class="inner clearfix">
        <section id="main-content">
          <h1 id="verror-rich-javascript-errors">verror: rich JavaScript errors</h1>

<p>This module provides several classes in support of Joyent’s <a href="http://www.joyent.com/developers/node/design/errors">Best Practices for
Error Handling in Node.js</a>.
If you find any of the behavior here confusing or surprising, check out that
document first.</p>

<p>The error classes here support:</p>

<ul>
  <li>printf-style arguments for the message</li>
  <li>chains of causes</li>
  <li>properties to provide extra information about the error</li>
  <li>creating your own subclasses that support all of these</li>
</ul>

<p>The classes here are:</p>

<ul>
  <li><strong>VError</strong>, for chaining errors while preserving each one’s error message.
This is useful in servers and command-line utilities when you want to
propagate an error up a call stack, but allow various levels to add their own
context.  See examples below.</li>
  <li><strong>WError</strong>, for wrapping errors while hiding the lower-level messages from the
top-level error.  This is useful for API endpoints where you don’t want to
expose internal error messages, but you still want to preserve the error chain
for logging and debugging.</li>
  <li><strong>SError</strong>, which is just like VError but interprets printf-style arguments
more strictly.</li>
  <li><strong>MultiError</strong>, which is just an Error that encapsulates one or more other
errors.  (This is used for parallel operations that return several errors.)</li>
</ul>

<h1 id="quick-start">Quick start</h1>

<p>First, install the package:</p>

<div class="highlighter-rouge"><div class="highlight"><pre class="highlight"><code>npm install verror
</code></pre></div></div>

<p>If nothing else, you can use VError as a drop-in replacement for the built-in
JavaScript Error class, with the addition of printf-style messages:</p>

<div class="language-javascript highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="kd">var</span> <span class="nx">err</span> <span class="o">=</span> <span class="k">new</span> <span class="nx">VError</span><span class="p">(</span><span class="s1">'missing file: "%s"'</span><span class="p">,</span> <span class="s1">'/etc/passwd'</span><span class="p">);</span>
<span class="nx">console</span><span class="p">.</span><span class="nx">log</span><span class="p">(</span><span class="nx">err</span><span class="p">.</span><span class="nx">message</span><span class="p">);</span>
</code></pre></div></div>

<p>This prints:</p>

<div class="highlighter-rouge"><div class="highlight"><pre class="highlight"><code>missing file: "/etc/passwd"
</code></pre></div></div>

<p>You can also pass a <code class="highlighter-rouge">cause</code> argument, which is any other Error object:</p>

<div class="language-javascript highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="kd">var</span> <span class="nx">fs</span> <span class="o">=</span> <span class="nx">require</span><span class="p">(</span><span class="s1">'fs'</span><span class="p">);</span>
<span class="kd">var</span> <span class="nx">filename</span> <span class="o">=</span> <span class="s1">'/nonexistent'</span><span class="p">;</span>
<span class="nx">fs</span><span class="p">.</span><span class="nx">stat</span><span class="p">(</span><span class="nx">filename</span><span class="p">,</span> <span class="kd">function</span> <span class="p">(</span><span class="nx">err1</span><span class="p">)</span> <span class="p">{</span>
	<span class="kd">var</span> <span class="nx">err2</span> <span class="o">=</span> <span class="k">new</span> <span class="nx">VError</span><span class="p">(</span><span class="nx">err1</span><span class="p">,</span> <span class="s1">'stat "%s"'</span><span class="p">,</span> <span class="nx">filename</span><span class="p">);</span>
	<span class="nx">console</span><span class="p">.</span><span class="nx">error</span><span class="p">(</span><span class="nx">err2</span><span class="p">.</span><span class="nx">message</span><span class="p">);</span>
<span class="p">});</span>
</code></pre></div></div>

<p>This prints out:</p>

<div class="highlighter-rouge"><div class="highlight"><pre class="highlight"><code>stat "/nonexistent": ENOENT, stat '/nonexistent'
</code></pre></div></div>

<p>which resembles how Unix programs typically report errors:</p>

<div class="highlighter-rouge"><div class="highlight"><pre class="highlight"><code>$ sort /nonexistent
sort: open failed: /nonexistent: No such file or directory
</code></pre></div></div>

<p>To match the Unixy feel, when you print out the error, just prepend the
program’s name to the VError’s <code class="highlighter-rouge">message</code>.  Or just call
<a href="https://github.com/joyent/node-cmdutil">node-cmdutil.fail(your_verror)</a>, which
does this for you.</p>

<p>You can get the next-level Error using <code class="highlighter-rouge">err.cause()</code>:</p>

<div class="language-javascript highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="nx">console</span><span class="p">.</span><span class="nx">error</span><span class="p">(</span><span class="nx">err2</span><span class="p">.</span><span class="nx">cause</span><span class="p">().</span><span class="nx">message</span><span class="p">);</span>
</code></pre></div></div>

<p>prints:</p>

<div class="highlighter-rouge"><div class="highlight"><pre class="highlight"><code>ENOENT, stat '/nonexistent'
</code></pre></div></div>

<p>Of course, you can chain these as many times as you want, and it works with any
kind of Error:</p>

<div class="language-javascript highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="kd">var</span> <span class="nx">err1</span> <span class="o">=</span> <span class="k">new</span> <span class="nb">Error</span><span class="p">(</span><span class="s1">'No such file or directory'</span><span class="p">);</span>
<span class="kd">var</span> <span class="nx">err2</span> <span class="o">=</span> <span class="k">new</span> <span class="nx">VError</span><span class="p">(</span><span class="nx">err1</span><span class="p">,</span> <span class="s1">'failed to stat "%s"'</span><span class="p">,</span> <span class="s1">'/junk'</span><span class="p">);</span>
<span class="kd">var</span> <span class="nx">err3</span> <span class="o">=</span> <span class="k">new</span> <span class="nx">VError</span><span class="p">(</span><span class="nx">err2</span><span class="p">,</span> <span class="s1">'request failed'</span><span class="p">);</span>
<span class="nx">console</span><span class="p">.</span><span class="nx">error</span><span class="p">(</span><span class="nx">err3</span><span class="p">.</span><span class="nx">message</span><span class="p">);</span>
</code></pre></div></div>

<p>This prints:</p>

<div class="highlighter-rouge"><div class="highlight"><pre class="highlight"><code>request failed: failed to stat "/junk": No such file or directory
</code></pre></div></div>

<p>The idea is that each layer in the stack annotates the error with a description
of what it was doing.  The end result is a message that explains what happened
at each level.</p>

<p>You can also decorate Error objects with additional information so that callers
can not only handle each kind of error differently, but also construct their own
error messages (e.g., to localize them, format them, group them by type, and so
on).  See the example below.</p>

<h1 id="deeper-dive">Deeper dive</h1>

<p>The two main goals for VError are:</p>

<ul>
  <li><strong>Make it easy to construct clear, complete error messages intended for
people.</strong>  Clear error messages greatly improve both user experience and
debuggability, so we wanted to make it easy to build them.  That’s why the
constructor takes printf-style arguments.</li>
  <li><strong>Make it easy to construct objects with programmatically-accessible
metadata</strong> (which we call <em>informational properties</em>).  Instead of just saying
“connection refused while connecting to 192.168.1.2:80”, you can add
properties like <code class="highlighter-rouge">"ip": "192.168.1.2"</code> and <code class="highlighter-rouge">"tcpPort": 80</code>.  This can be used
for feeding into monitoring systems, analyzing large numbers of Errors (as
from a log file), or localizing error messages.</li>
</ul>

<p>To really make this useful, it also needs to be easy to compose Errors:
higher-level code should be able to augment the Errors reported by lower-level
code to provide a more complete description of what happened.  Instead of saying
“connection refused”, you can say “operation X failed: connection refused”.
That’s why VError supports <code class="highlighter-rouge">causes</code>.</p>

<p>In order for all this to work, programmers need to know that it’s generally safe
to wrap lower-level Errors with higher-level ones.  If you have existing code
that handles Errors produced by a library, you should be able to wrap those
Errors with a VError to add information without breaking the error handling
code.  There are two obvious ways that this could break such consumers:</p>

<ul>
  <li>The error’s name might change.  People typically use <code class="highlighter-rouge">name</code> to determine what
kind of Error they’ve got.  To ensure compatibility, you can create VErrors
with custom names, but this approach isn’t great because it prevents you from
representing complex failures.  For this reason, VError provides
<code class="highlighter-rouge">findCauseByName</code>, which essentially asks: does this Error <em>or any of its
causes</em> have this specific type?  If error handling code uses
<code class="highlighter-rouge">findCauseByName</code>, then subsystems can construct very specific causal chains
for debuggability and still let people handle simple cases easily.  There’s an
example below.</li>
  <li>The error’s properties might change.  People often hang additional properties
off of Error objects.  If we wrap an existing Error in a new Error, those
properties would be lost unless we copied them.  But there are a variety of
both standard and non-standard Error properties that should <em>not</em> be copied in
this way: most obviously <code class="highlighter-rouge">name</code>, <code class="highlighter-rouge">message</code>, and <code class="highlighter-rouge">stack</code>, but also <code class="highlighter-rouge">fileName</code>,
<code class="highlighter-rouge">lineNumber</code>, and a few others.  Plus, it’s useful for some Error subclasses
to have their own private properties – and there’d be no way to know whether
these should be copied.  For these reasons, VError first-classes these
information properties.  You have to provide them in the constructor, you can
only fetch them with the <code class="highlighter-rouge">info()</code> function, and VError takes care of making
sure properties from causes wind up in the <code class="highlighter-rouge">info()</code> output.</li>
</ul>

<p>Let’s put this all together with an example from the node-fast RPC library.
node-fast implements a simple RPC protocol for Node programs.  There’s a server
and client interface, and clients make RPC requests to servers.  Let’s say the
server fails with an UnauthorizedError with message “user ‘bob’ is not
authorized”.  The client wraps all server errors with a FastServerError.  The
client also wraps all request errors with a FastRequestError that includes the
name of the RPC call being made.  The result of this failed RPC might look like
this:</p>

<div class="highlighter-rouge"><div class="highlight"><pre class="highlight"><code>name: FastRequestError
message: "request failed: server error: user 'bob' is not authorized"
rpcMsgid: &lt;unique identifier for this request&gt;
rpcMethod: GetObject
cause:
    name: FastServerError
    message: "server error: user 'bob' is not authorized"
    cause:
        name: UnauthorizedError
        message: "user 'bob' is not authorized"
        rpcUser: "bob"
</code></pre></div></div>

<p>When the caller uses <code class="highlighter-rouge">VError.info()</code>, the information properties are collapsed
so that it looks like this:</p>

<div class="highlighter-rouge"><div class="highlight"><pre class="highlight"><code>message: "request failed: server error: user 'bob' is not authorized"
rpcMsgid: &lt;unique identifier for this request&gt;
rpcMethod: GetObject
rpcUser: "bob"
</code></pre></div></div>

<p>Taking this apart:</p>

<ul>
  <li>The error’s message is a complete description of the problem.  The caller can
report this directly to its caller, which can potentially make its way back to
an end user (if appropriate).  It can also be logged.</li>
  <li>The caller can tell that the request failed on the server, rather than as a
result of a client problem (e.g., failure to serialize the request), a
transport problem (e.g., failure to connect to the server), or something else
(e.g., a timeout).  They do this using <code class="highlighter-rouge">findCauseByName('FastServerError')</code>
rather than checking the <code class="highlighter-rouge">name</code> field directly.</li>
  <li>If the caller logs this error, the logs can be analyzed to aggregate
errors by cause, by RPC method name, by user, or whatever.  Or the
error can be correlated with other events for the same rpcMsgid.</li>
  <li>It wasn’t very hard for any part of the code to contribute to this Error.
Each part of the stack has just a few lines to provide exactly what it knows,
with very little boilerplate.</li>
</ul>

<p>It’s not expected that you’d use these complex forms all the time.  Despite
supporting the complex case above, you can still just do:</p>

<p>new VError(“my service isn’t working”);</p>

<p>for the simple cases.</p>

<h1 id="reference-verror-werror-serror">Reference: VError, WError, SError</h1>

<p>VError, WError, and SError are convenient drop-in replacements for <code class="highlighter-rouge">Error</code> that
support printf-style arguments, first-class causes, informational properties,
and other useful features.</p>

<h2 id="constructors">Constructors</h2>

<p>The VError constructor has several forms:</p>

<div class="language-javascript highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="cm">/*
 * This is the most general form.  You can specify any supported options
 * (including "cause" and "info") this way.
 */</span>
<span class="k">new</span> <span class="nx">VError</span><span class="p">(</span><span class="nx">options</span><span class="p">,</span> <span class="nx">sprintf_args</span><span class="p">...)</span>

<span class="cm">/*
 * This is a useful shorthand when the only option you need is "cause".
 */</span>
<span class="k">new</span> <span class="nx">VError</span><span class="p">(</span><span class="nx">cause</span><span class="p">,</span> <span class="nx">sprintf_args</span><span class="p">...)</span>

<span class="cm">/*
 * This is a useful shorthand when you don't need any options at all.
 */</span>
<span class="k">new</span> <span class="nx">VError</span><span class="p">(</span><span class="nx">sprintf_args</span><span class="p">...)</span>
</code></pre></div></div>

<p>All of these forms construct a new VError that behaves just like the built-in
JavaScript <code class="highlighter-rouge">Error</code> class, with some additional methods described below.</p>

<p>In the first form, <code class="highlighter-rouge">options</code> is a plain object with any of the following
optional properties:</p>

<table>
  <thead>
    <tr>
      <th>Option name</th>
      <th>Type</th>
      <th>Meaning</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><code class="highlighter-rouge">name</code></td>
      <td>string</td>
      <td>Describes what kind of error this is.  This is intended for programmatic use to distinguish between different kinds of errors.  Note that in modern versions of Node.js, this name is ignored in the <code class="highlighter-rouge">stack</code> property value, but callers can still use the <code class="highlighter-rouge">name</code> property to get at it.</td>
    </tr>
    <tr>
      <td><code class="highlighter-rouge">cause</code></td>
      <td>any Error object</td>
      <td>Indicates that the new error was caused by <code class="highlighter-rouge">cause</code>.  See <code class="highlighter-rouge">cause()</code> below.  If unspecified, the cause will be <code class="highlighter-rouge">null</code>.</td>
    </tr>
    <tr>
      <td><code class="highlighter-rouge">strict</code></td>
      <td>boolean</td>
      <td>If true, then <code class="highlighter-rouge">null</code> and <code class="highlighter-rouge">undefined</code> values in <code class="highlighter-rouge">sprintf_args</code> are passed through to <code class="highlighter-rouge">sprintf()</code>.  Otherwise, these are replaced with the strings <code class="highlighter-rouge">'null'</code>, and ‘<code class="highlighter-rouge">undefined</code>’, respectively.</td>
    </tr>
    <tr>
      <td><code class="highlighter-rouge">constructorOpt</code></td>
      <td>function</td>
      <td>If specified, then the stack trace for this error ends at function <code class="highlighter-rouge">constructorOpt</code>.  Functions called by <code class="highlighter-rouge">constructorOpt</code> will not show up in the stack.  This is useful when this class is subclassed.</td>
    </tr>
    <tr>
      <td><code class="highlighter-rouge">info</code></td>
      <td>object</td>
      <td>Specifies arbitrary informational properties that are available through the <code class="highlighter-rouge">VError.info(err)</code> static class method.  See that method for details.</td>
    </tr>
  </tbody>
</table>

<p>The second form is equivalent to using the first form with the specified <code class="highlighter-rouge">cause</code>
as the error’s cause.  This form is distinguished from the first form because
the first argument is an Error.</p>

<p>The third form is equivalent to using the first form with all default option
values.  This form is distinguished from the other forms because the first
argument is not an object or an Error.</p>

<p>The <code class="highlighter-rouge">WError</code> constructor is used exactly the same way as the <code class="highlighter-rouge">VError</code>
constructor.  The <code class="highlighter-rouge">SError</code> constructor is also used the same way as the
<code class="highlighter-rouge">VError</code> constructor except that in all cases, the <code class="highlighter-rouge">strict</code> property is
overriden to `true.</p>

<h2 id="public-properties">Public properties</h2>

<p><code class="highlighter-rouge">VError</code>, <code class="highlighter-rouge">WError</code>, and <code class="highlighter-rouge">SError</code> all provide the same public properties as
JavaScript’s built-in Error objects.</p>

<table>
  <thead>
    <tr>
      <th>Property name</th>
      <th>Type</th>
      <th>Meaning</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><code class="highlighter-rouge">name</code></td>
      <td>string</td>
      <td>Programmatically-usable name of the error.</td>
    </tr>
    <tr>
      <td><code class="highlighter-rouge">message</code></td>
      <td>string</td>
      <td>Human-readable summary of the failure.  Programmatically-accessible details are provided through <code class="highlighter-rouge">VError.info(err)</code> class method.</td>
    </tr>
    <tr>
      <td><code class="highlighter-rouge">stack</code></td>
      <td>string</td>
      <td>Human-readable stack trace where the Error was constructed.</td>
    </tr>
  </tbody>
</table>

<p>For all of these classes, the printf-style arguments passed to the constructor
are processed with <code class="highlighter-rouge">sprintf()</code> to form a message.  For <code class="highlighter-rouge">WError</code>, this becomes
the complete <code class="highlighter-rouge">message</code> property.  For <code class="highlighter-rouge">SError</code> and <code class="highlighter-rouge">VError</code>, this message is
prepended to the message of the cause, if any (with a suitable separator), and
the result becomes the <code class="highlighter-rouge">message</code> property.</p>

<p>The <code class="highlighter-rouge">stack</code> property is managed entirely by the underlying JavaScript
implementation.  It’s generally implemented using a getter function because
constructing the human-readable stack trace is somewhat expensive.</p>

<h2 id="class-methods">Class methods</h2>

<p>The following methods are defined on the <code class="highlighter-rouge">VError</code> class and as exported
functions on the <code class="highlighter-rouge">verror</code> module.  They’re defined this way rather than using
methods on VError instances so that they can be used on Errors not created with
<code class="highlighter-rouge">VError</code>.</p>

<h3 id="verrorcauseerr"><code class="highlighter-rouge">VError.cause(err)</code></h3>

<p>The <code class="highlighter-rouge">cause()</code> function returns the next Error in the cause chain for <code class="highlighter-rouge">err</code>, or
<code class="highlighter-rouge">null</code> if there is no next error.  See the <code class="highlighter-rouge">cause</code> argument to the constructor.
Errors can have arbitrarily long cause chains.  You can walk the <code class="highlighter-rouge">cause</code> chain
by invoking <code class="highlighter-rouge">VError.cause(err)</code> on each subsequent return value.  If <code class="highlighter-rouge">err</code> is
not a <code class="highlighter-rouge">VError</code>, the cause is <code class="highlighter-rouge">null</code>.</p>

<h3 id="verrorinfoerr"><code class="highlighter-rouge">VError.info(err)</code></h3>

<p>Returns an object with all of the extra error information that’s been associated
with this Error and all of its causes.  These are the properties passed in using
the <code class="highlighter-rouge">info</code> option to the constructor.  Properties not specified in the
constructor for this Error are implicitly inherited from this error’s cause.</p>

<p>These properties are intended to provide programmatically-accessible metadata
about the error.  For an error that indicates a failure to resolve a DNS name,
informational properties might include the DNS name to be resolved, or even the
list of resolvers used to resolve it.  The values of these properties should
generally be plain objects (i.e., consisting only of null, undefined, numbers,
booleans, strings, and objects and arrays containing only other plain objects).</p>

<h3 id="verrorfullstackerr"><code class="highlighter-rouge">VError.fullStack(err)</code></h3>

<p>Returns a string containing the full stack trace, with all nested errors recursively
reported as <code class="highlighter-rouge">'caused by:' + err.stack</code>.</p>

<h3 id="verrorfindcausebynameerr-name"><code class="highlighter-rouge">VError.findCauseByName(err, name)</code></h3>

<p>The <code class="highlighter-rouge">findCauseByName()</code> function traverses the cause chain for <code class="highlighter-rouge">err</code>, looking
for an error whose <code class="highlighter-rouge">name</code> property matches the passed in <code class="highlighter-rouge">name</code> value. If no
match is found, <code class="highlighter-rouge">null</code> is returned.</p>

<p>If all you want is to know <em>whether</em> there’s a cause (and you don’t care what it
is), you can use <code class="highlighter-rouge">VError.hasCauseWithName(err, name)</code>.</p>

<p>If a vanilla error or a non-VError error is passed in, then there is no cause
chain to traverse. In this scenario, the function will check the <code class="highlighter-rouge">name</code>
property of only <code class="highlighter-rouge">err</code>.</p>

<h3 id="verrorhascausewithnameerr-name"><code class="highlighter-rouge">VError.hasCauseWithName(err, name)</code></h3>

<p>Returns true if and only if <code class="highlighter-rouge">VError.findCauseByName(err, name)</code> would return
a non-null value.  This essentially determines whether <code class="highlighter-rouge">err</code> has any cause in
its cause chain that has name <code class="highlighter-rouge">name</code>.</p>

<h3 id="verrorerrorfromlisterrors"><code class="highlighter-rouge">VError.errorFromList(errors)</code></h3>

<p>Given an array of Error objects (possibly empty), return a single error
representing the whole collection of errors.  If the list has:</p>

<ul>
  <li>0 elements, returns <code class="highlighter-rouge">null</code></li>
  <li>1 element, returns the sole error</li>
  <li>more than 1 element, returns a MultiError referencing the whole list</li>
</ul>

<p>This is useful for cases where an operation may produce any number of errors,
and you ultimately want to implement the usual <code class="highlighter-rouge">callback(err)</code> pattern.  You can
accumulate the errors in an array and then invoke
<code class="highlighter-rouge">callback(VError.errorFromList(errors))</code> when the operation is complete.</p>

<h3 id="verrorerrorforeacherr-func"><code class="highlighter-rouge">VError.errorForEach(err, func)</code></h3>

<p>Convenience function for iterating an error that may itself be a MultiError.</p>

<p>In all cases, <code class="highlighter-rouge">err</code> must be an Error.  If <code class="highlighter-rouge">err</code> is a MultiError, then <code class="highlighter-rouge">func</code> is
invoked as <code class="highlighter-rouge">func(errorN)</code> for each of the underlying errors of the MultiError.
If <code class="highlighter-rouge">err</code> is any other kind of error, <code class="highlighter-rouge">func</code> is invoked once as <code class="highlighter-rouge">func(err)</code>.  In
all cases, <code class="highlighter-rouge">func</code> is invoked synchronously.</p>

<p>This is useful for cases where an operation may produce any number of warnings
that may be encapsulated with a MultiError – but may not be.</p>

<p>This function does not iterate an error’s cause chain.</p>

<h2 id="examples">Examples</h2>

<p>The “Demo” section above covers several basic cases.  Here’s a more advanced
case:</p>

<div class="language-javascript highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="kd">var</span> <span class="nx">err1</span> <span class="o">=</span> <span class="k">new</span> <span class="nx">VError</span><span class="p">(</span><span class="s1">'something bad happened'</span><span class="p">);</span>
<span class="cm">/* ... */</span>
<span class="kd">var</span> <span class="nx">err2</span> <span class="o">=</span> <span class="k">new</span> <span class="nx">VError</span><span class="p">({</span>
    <span class="s1">'name'</span><span class="p">:</span> <span class="s1">'ConnectionError'</span><span class="p">,</span>
    <span class="s1">'cause'</span><span class="p">:</span> <span class="nx">err1</span><span class="p">,</span>
    <span class="s1">'info'</span><span class="p">:</span> <span class="p">{</span>
        <span class="s1">'errno'</span><span class="p">:</span> <span class="s1">'ECONNREFUSED'</span><span class="p">,</span>
        <span class="s1">'remote_ip'</span><span class="p">:</span> <span class="s1">'127.0.0.1'</span><span class="p">,</span>
        <span class="s1">'port'</span><span class="p">:</span> <span class="mi">215</span>
    <span class="p">}</span>
<span class="p">},</span> <span class="s1">'failed to connect to "%s:%d"'</span><span class="p">,</span> <span class="s1">'127.0.0.1'</span><span class="p">,</span> <span class="mi">215</span><span class="p">);</span>

<span class="nx">console</span><span class="p">.</span><span class="nx">log</span><span class="p">(</span><span class="nx">err2</span><span class="p">.</span><span class="nx">message</span><span class="p">);</span>
<span class="nx">console</span><span class="p">.</span><span class="nx">log</span><span class="p">(</span><span class="nx">err2</span><span class="p">.</span><span class="nx">name</span><span class="p">);</span>
<span class="nx">console</span><span class="p">.</span><span class="nx">log</span><span class="p">(</span><span class="nx">VError</span><span class="p">.</span><span class="nx">info</span><span class="p">(</span><span class="nx">err2</span><span class="p">));</span>
<span class="nx">console</span><span class="p">.</span><span class="nx">log</span><span class="p">(</span><span class="nx">err2</span><span class="p">.</span><span class="nx">stack</span><span class="p">);</span>
</code></pre></div></div>

<p>This outputs:</p>

<div class="highlighter-rouge"><div class="highlight"><pre class="highlight"><code>failed to connect to "127.0.0.1:215": something bad happened
ConnectionError
{ errno: 'ECONNREFUSED', remote_ip: '127.0.0.1', port: 215 }
ConnectionError: failed to connect to "127.0.0.1:215": something bad happened
    at Object.&lt;anonymous&gt; (/home/dap/node-verror/examples/info.js:5:12)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:935:3
</code></pre></div></div>

<p>Information properties are inherited up the cause chain, with values at the top
of the chain overriding same-named values lower in the chain.  To continue that
example:</p>

<div class="language-javascript highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="kd">var</span> <span class="nx">err3</span> <span class="o">=</span> <span class="k">new</span> <span class="nx">VError</span><span class="p">({</span>
    <span class="s1">'name'</span><span class="p">:</span> <span class="s1">'RequestError'</span><span class="p">,</span>
    <span class="s1">'cause'</span><span class="p">:</span> <span class="nx">err2</span><span class="p">,</span>
    <span class="s1">'info'</span><span class="p">:</span> <span class="p">{</span>
        <span class="s1">'errno'</span><span class="p">:</span> <span class="s1">'EBADREQUEST'</span>
    <span class="p">}</span>
<span class="p">},</span> <span class="s1">'request failed'</span><span class="p">);</span>

<span class="nx">console</span><span class="p">.</span><span class="nx">log</span><span class="p">(</span><span class="nx">err3</span><span class="p">.</span><span class="nx">message</span><span class="p">);</span>
<span class="nx">console</span><span class="p">.</span><span class="nx">log</span><span class="p">(</span><span class="nx">err3</span><span class="p">.</span><span class="nx">name</span><span class="p">);</span>
<span class="nx">console</span><span class="p">.</span><span class="nx">log</span><span class="p">(</span><span class="nx">VError</span><span class="p">.</span><span class="nx">info</span><span class="p">(</span><span class="nx">err3</span><span class="p">));</span>
<span class="nx">console</span><span class="p">.</span><span class="nx">log</span><span class="p">(</span><span class="nx">err3</span><span class="p">.</span><span class="nx">stack</span><span class="p">);</span>
</code></pre></div></div>

<p>This outputs:</p>

<div class="highlighter-rouge"><div class="highlight"><pre class="highlight"><code>request failed: failed to connect to "127.0.0.1:215": something bad happened
RequestError
{ errno: 'EBADREQUEST', remote_ip: '127.0.0.1', port: 215 }
RequestError: request failed: failed to connect to "127.0.0.1:215": something bad happened
    at Object.&lt;anonymous&gt; (/home/dap/node-verror/examples/info.js:20:12)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:935:3
</code></pre></div></div>

<p>You can also print the complete stack trace of combined <code class="highlighter-rouge">Error</code>s by using
<code class="highlighter-rouge">VError.fullStack(err).</code></p>

<div class="language-javascript highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="kd">var</span> <span class="nx">err1</span> <span class="o">=</span> <span class="k">new</span> <span class="nx">VError</span><span class="p">(</span><span class="s1">'something bad happened'</span><span class="p">);</span>
<span class="cm">/* ... */</span>
<span class="kd">var</span> <span class="nx">err2</span> <span class="o">=</span> <span class="k">new</span> <span class="nx">VError</span><span class="p">(</span><span class="nx">err1</span><span class="p">,</span> <span class="s1">'something really bad happened here'</span><span class="p">);</span>

<span class="nx">console</span><span class="p">.</span><span class="nx">log</span><span class="p">(</span><span class="nx">VError</span><span class="p">.</span><span class="nx">fullStack</span><span class="p">(</span><span class="nx">err2</span><span class="p">));</span>
</code></pre></div></div>

<p>This outputs:</p>

<div class="highlighter-rouge"><div class="highlight"><pre class="highlight"><code>VError: something really bad happened here: something bad happened
    at Object.&lt;anonymous&gt; (/home/dap/node-verror/examples/fullStack.js:5:12)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
    at node.js:968:3
caused by: VError: something bad happened
    at Object.&lt;anonymous&gt; (/home/dap/node-verror/examples/fullStack.js:3:12)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
    at node.js:968:3
</code></pre></div></div>

<p><code class="highlighter-rouge">VError.fullStack</code> is also safe to use on regular <code class="highlighter-rouge">Error</code>s, so feel free to use
it whenever you need to extract the stack trace from an <code class="highlighter-rouge">Error</code>, regardless if
it’s a <code class="highlighter-rouge">VError</code> or not.</p>

<h1 id="reference-multierror">Reference: MultiError</h1>

<p>MultiError is an Error class that represents a group of Errors.  This is used
when you logically need to provide a single Error, but you want to preserve
information about multiple underying Errors.  A common case is when you execute
several operations in parallel and some of them fail.</p>

<p>MultiErrors are constructed as:</p>

<div class="language-javascript highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="k">new</span> <span class="nx">MultiError</span><span class="p">(</span><span class="nx">error_list</span><span class="p">)</span>
</code></pre></div></div>

<p><code class="highlighter-rouge">error_list</code> is an array of at least one <code class="highlighter-rouge">Error</code> object.</p>

<p>The cause of the MultiError is the first error provided.  None of the other
<code class="highlighter-rouge">VError</code> options are supported.  The <code class="highlighter-rouge">message</code> for a MultiError consists the
<code class="highlighter-rouge">message</code> from the first error, prepended with a message indicating that there
were other errors.</p>

<p>For example:</p>

<div class="language-javascript highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="nx">err</span> <span class="o">=</span> <span class="k">new</span> <span class="nx">MultiError</span><span class="p">([</span>
    <span class="k">new</span> <span class="nb">Error</span><span class="p">(</span><span class="s1">'failed to resolve DNS name "abc.example.com"'</span><span class="p">),</span>
    <span class="k">new</span> <span class="nb">Error</span><span class="p">(</span><span class="s1">'failed to resolve DNS name "def.example.com"'</span><span class="p">),</span>
<span class="p">]);</span>

<span class="nx">console</span><span class="p">.</span><span class="nx">error</span><span class="p">(</span><span class="nx">err</span><span class="p">.</span><span class="nx">message</span><span class="p">);</span>
</code></pre></div></div>

<p>outputs:</p>

<div class="highlighter-rouge"><div class="highlight"><pre class="highlight"><code>first of 2 errors: failed to resolve DNS name "abc.example.com"
</code></pre></div></div>

<p>See the convenience function <code class="highlighter-rouge">VError.errorFromList</code>, which is sometimes simpler
to use than this constructor.</p>

<h2 id="public-methods">Public methods</h2>

<h3 id="errors"><code class="highlighter-rouge">errors()</code></h3>

<p>Returns an array of the errors used to construct this MultiError.</p>

<h1 id="contributing">Contributing</h1>

<p>See separate <a href="/FlutterArsenal/fromgithub/node_modules/verror/CONTRIBUTING.md">contribution guidelines</a>.</p>

        </section>

        <aside id="sidebar">
          

          
            <p class="repo-owner"><a href="https://github.com/karx/karx.github.io">karx.github.io</a> is maintained by <a href="https://github.com/karx">karx</a>.</p>
          

          <p>This page was generated by <a href="https://pages.github.com">GitHub Pages</a>.</p>
        </aside>
      </div>
    </div>

    
  </body>
</html>
